CREATE TABLE NHANVIEN
(
	IDNhanVien NCHAR(10) PRIMARY KEY,
	Password NCHAR(20),
	Name NVARCHAR(50),
	PhoneNumber INT,
	IDCard INT,
	Address NVARCHAR(100),
	IDHistorySell NCHAR(10),
	Position NCHAR(10)
)
CREATE TABLE SANPHAM
(
	IDSanPham NCHAR(10) PRIMARY KEY,
	IDCategory NCHAR(10),
	Name NVARCHAR(50),
	Price INT,
	IDBlock NCHAR(10),
	IDDetail NCHAR(10),
	DateSell NVARCHAR(50)
)
CREATE TABLE CATEGORY
(
	IDCategory NCHAR(10) PRIMARY KEY,
	Name NVARCHAR(50),
	Quantity INT,
)
CREATE TABLE KHACHHANG
(
	IDKhachHang NCHAR(10) PRIMARY KEY,
	Name NVARCHAR(50),
	phoneNumber INT,
	Address NVARCHAR(100),
	IDKhuyenMai NCHAR(10)
)
CREATE TABLE BLOCK
(
	IDBlock NCHAR(10) PRIMARY KEY,
	Name NVARCHAR(50)
)
CREATE TABLE DETAIL
(
	IDDetail NCHAR(10) PRIMARY KEY,
	ManHinh NVARCHAR(50),
	CameraTruoc NVARCHAR(50),
	CameraSau NVARCHAR(50),
	OS NVARCHAR(50),
	Ram NVARCHAR(50),
	Rom NVARCHAR(50),
	DungLuongPin NVARCHAR(50),
	Chip NVARCHAR(50)
)
CREATE TABLE HISTORY
(
	IDLichSu NCHAR(10) PRIMARY KEY,
	IDNhanVien NCHAR(10),
	IDKhachHang NCHAR(10),
	NgayBan DATE,
	NgayLuuKho DATE,
	IDCategory NCHAR(10)
)
CREATE TABLE THONGBAO
(
	IDNhanVien NCHAR(10),
	TrangThai BIT,
	NoiDung NVARCHAR(1000)
)
CREATE TABLE KHUYENMAI
(
	IDKhuyenMai NCHAR(10) PRIMARY KEY,
	GiamGia NVARCHAR(10)
)
CREATE TABLE HOADON
(
	IDHoaDon NCHAR(10) PRIMARY KEY,
	IDNhanVien NCHAR(10),
	IDKhachHang NCHAR(10),
	TongTien INT,
	NgayBan DATE,
	IDKhuyenMai NCHAR(10),
	TongTienCuoi INT
)
CREATE TABLE CHITIETHOADON
(
	IDHoaDon NCHAR(10),
	IDSanPham NCHAR(10),
	DonGia INT
)